// svelte/src/pages/HelloWorld/HelloWorldForm.svelte
<script type="ts">
    import "@material/mwc-button";
    import "@material/mwc-textfield";
    import type { TextField } from "@material/mwc-textfield";
    import { onDestroy, onMount, tick } from "svelte";
    import { helloWorldService } from "shared";

    let isValid = false;
    let form: HTMLFormElement;
    let name: TextField;

    function checkValidity(): boolean {
        return form.checkValidity() && name.checkValidity();
    }

    function clearForm(): void {
        name.value = "";
        name.focus();
    }

    function getFormData(): any {
        const formData = new FormData(form);
        const data = {};
        for (let [key, value] of formData) {
            data[key] = value;
        }
        return data;
    }

    function handleFormDataChanged(event: Event) {
        isValid = checkValidity();
    }

    function handleKeyup(event: KeyboardEvent) {
        if (event.code === "Enter") {
            event.preventDefault();
            handleSubmit(event);
        }
    }

    function handleNameInvalid(event: InputEvent) {
        isValid = false;

        name.validationMessage = "";
        if (name.validity.valueMissing) {
            name.validationMessage = "Name is required";
        } else if (name.validity.tooShort) {
            name.validationMessage = `Name must be at least ${name.getAttribute("minlength")} characters long`;
        } else if (name.validity.customError) {
            name.validationMessage = "Names starting with 'D' must be 'Doug'";
        }
    }

    function handleSubmit(event: Event) {
        event.preventDefault();

        if (!checkValidity()) {
            return;
        }

        // If succcessful, send data to server
        const data = getFormData();
        helloWorldService.createHelloWorld({ sayHelloCommandMessage: data }).subscribe(() => {
            clearForm();
        });
    }

    onMount(async () => {
        form.addEventListener("change", handleFormDataChanged);
        name.addEventListener("keyup", handleKeyup);
        name.addEventListener("invalid", handleNameInvalid);
        name.validityTransform = (newValue, nativeValidity) => {
            if (newValue.startsWith("D") && newValue !== "Doug") {
                return {
                    ...nativeValidity,
                    customError: true,
                    valid: false,
                };
            }
            return nativeValidity;
        };

        await tick();
        name.focus();
    });
    onDestroy(() => {
        form.removeEventListener("change", handleFormDataChanged);
        name.removeEventListener("keyup", handleKeyup);
        name.removeEventListener("invalid", handleNameInvalid);
    });
</script>

<form bind:this={form} on:submit={handleSubmit}>
    <div class="spaced">
        <mwc-textfield
            bind:this={name}
            label="Hello, "
            minLength="2"
            name="name"
            placeholder="Name"
            required
            autoValidate
        />
    </div>
    <div class="right"><mwc-button disabled={!isValid} raised on:click={handleSubmit}>Submit</mwc-button></div>
</form>

<style>
    .spaced {
        margin-bottom: 16px;
    }

    .right {
        text-align: right;
    }
</style>

// react/src/pages/HelloWorld/HelloWorldForm.tsx
import "@material/mwc-button";
import "@material/mwc-textfield";
import type { TextField } from "@material/mwc-textfield";
import { FormEvent, useEffect, useRef, useState } from "react";
import { helloWorldService } from "shared";
import "./HelloWorldForm.css";

function HelloWorldForm() {
    const [isValid, setIsValid] = useState(false);

    const formRef = useRef<HTMLFormElement>(null);
    const nameRef = useRef<TextField>(null);

    useEffect(() => {
        const nameField = nameRef.current;
        if (nameField) {
            nameField.addEventListener("invalid", handleNameInvalid);
            nameField.addEventListener("keydown", handleKeyDown);

            nameField.validityTransform = (newValue, nativeValidity) => {
                if (newValue.startsWith("D") && newValue !== "Doug") {
                    return {
                        ...nativeValidity,
                        customError: true,
                        valid: false,
                    };
                }
                return nativeValidity;
            };

            nameField.focus(); // Set initial focus on the name field
        }

        return () => {
            nameField?.removeEventListener("invalid", handleNameInvalid);
            nameField?.removeEventListener("keydown", handleKeyDown);
        };
    }, []);

    const checkValidity = () => {
        return (formRef?.current?.checkValidity() && nameRef?.current?.checkValidity()) ?? false;
    };

    const clearForm = () => {
        if (nameRef.current) {
            nameRef.current.value = "";
            nameRef.current.focus();
        }
    };

    const getFormData = (): any => {
        if (formRef?.current) {
            const formData = new FormData(formRef.current);
            const data: any = {};
            for (let [key, value] of formData) {
                data[key] = value;
            }
            return data;
        }

        return {};
    };

    const handleFormDataChanged = (event: FormEvent) => {
        setIsValid(checkValidity());
    };

    const handleKeyDown = (event: KeyboardEvent) => {
        if (event.code === "Enter") {
            event.preventDefault();
            submit();
        }
    };

    const handleNameInvalid = (event: Event) => {
        setIsValid(false);

        const nameField = nameRef.current;
        if (nameField) {
            nameField.validationMessage = "";
            if (nameField.validity.valueMissing) {
                nameField.validationMessage = "Name is required";
            } else if (nameField.validity.tooShort) {
                nameField.validationMessage = `Name must be at least ${nameField.getAttribute(
                    "minlength",
                )} characters long`;
            } else if (nameField.validity.customError) {
                nameField.validationMessage = "Names starting with 'D' must be 'Doug'";
            }
        }
    };

    const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();

        submit();
    };

    const submit = () => {
        if (!checkValidity()) {
            return;
        }
        const data = getFormData();

        helloWorldService.createHelloWorld({ sayHelloCommandMessage: data }).subscribe(clearForm);
    };

    return (
        <form ref={formRef} onChange={handleFormDataChanged} onSubmit={handleSubmit}>
            <div className="spaced">
                <mwc-textfield
                    ref={nameRef}
                    autoValidate
                    label="Hello, "
                    minLength="2"
                    name="name"
                    placeholder="Name"
                    required
                />
            </div>
            <div className="right">
                <mwc-button onClick={handleSubmit} raised>
                    Submit
                </mwc-button>
            </div>
        </form>
    );
}

export default HelloWorldForm;
