// react-app/src/App.tsx
import { useEffect, useRef } from "react";
import "./App.css";
import "@material/mwc-drawer";
import type { Drawer } from "@material/mwc-drawer";
import "@material/mwc-icon";
import "@material/mwc-icon-button";
import "@material/mwc-top-app-bar-fixed";

declare global {
    namespace JSX {
        interface IntrinsicElements {
            "mwc-drawer": any;
            "mwc-icon": any;
            "mwc-icon-button": any;
            "mwc-top-app-bar-fixed": any;
        }
    }
}

function App() {
    const drawerRef = useRef<Drawer>();

    const handleNavigationClick = () => {
        if (drawerRef.current) {
            drawerRef.current.open = !drawerRef.current.open;
        }
    };

    useEffect(() => {
        const drawer = drawerRef.current;
        if (drawer) {
            drawer.addEventListener("MDCTopAppBar:nav", handleNavigationClick);
        }

        return () => {
            drawer?.removeEventListener("MDCTopAppBar:nav", handleNavigationClick);
        };
    }, []);

    return (
        <mwc-drawer ref={drawerRef} hasHeader type="modal">
            <span slot="title">Hello World!</span>
            <div>
                <ul>
                    <li>
                        <a href="#/">
                            <mwc-icon>home</mwc-icon> Home
                        </a>
                    </li>
                    <li>
                        <a href="#/hello-world">
                            <mwc-icon>language</mwc-icon> Hello World!
                        </a>
                    </li>
                </ul>
            </div>
            <div slot="appContent">
                <mwc-top-app-bar-fixed dense>
                    <slot name="title" slot="title" />
                    <slot name="actionItems" slot="actionItems" />
                    <mwc-icon-button icon="menu" slot="navigationIcon" />
                    <slot />
                </mwc-top-app-bar-fixed>
            </div>
        </mwc-drawer>
    );
}

export default App;

// angular/src/app/app.component.ts
import { AfterContentInit, Component, ElementRef, OnDestroy, ViewChild } from "@angular/core";
import "@material/mwc-drawer";
import { Drawer } from "@material/mwc-drawer";
import "@material/mwc-icon";
import "@material/mwc-icon-button";
import "@material/mwc-list";
import "@material/mwc-top-app-bar-fixed";

@Component({
    selector: "app-root",
    templateUrl: "./app.component.html",
    styleUrls: ["./app.component.css"],
})
export class AppComponent implements AfterContentInit, OnDestroy {
    private drawer: Drawer | null;

    constructor(private elementRef: ElementRef<HTMLElement>) {}

    handleNavigationClick() {
        if (this.drawer) {
            this.drawer.open = !this.drawer.open;
        }
    }

    ngAfterContentInit(): void {
        this.drawer = this.elementRef.nativeElement.querySelector<Drawer>("mwc-drawer");
        this.elementRef.nativeElement.addEventListener("MDCTopAppBar:nav", () => this.handleNavigationClick());
    }

    ngOnDestroy(): void {
        this.elementRef.nativeElement.removeEventListener("MDCTopAppBar:nav", () => this.handleNavigationClick());
    }
}

<mwc-drawer #drawer hasHeader type="modal">
    <span slot="title">Hello World!</span>
    <mwc-list rootTabbable>
        <a routerLink="/">
            <mwc-list-item tabindex="0" graphic="avatar">
                Home
                <mwc-icon slot="graphic">home</mwc-icon>
            </mwc-list-item>
        </a>
        <li divider role="separator"></li>
        <a routerLink="/hello-world">
            <mwc-list-item tabindex="0" graphic="avatar">
                Hello World!
                <mwc-icon slot="graphic">language</mwc-icon>
            </mwc-list-item>
        </a>
    </mwc-list>

    <div slot="appContent">
        <mwc-top-app-bar-fixed dense>
            <router-outlet name="title"></router-outlet>
            <router-outlet name="actionItems"></router-outlet>
            <mwc-icon-button icon="menu" slot="navigationIcon"></mwc-icon-button>
            <router-outlet></router-outlet>
        </mwc-top-app-bar-fixed>
    </div>
</mwc-drawer>
