// react/src/pages/Home.tsx
import { Link } from "react-router-dom";
import { layoutService } from "../services/LayoutService";
import "./Home.css";

function Home() {
    layoutService.setTitle(<span>Home(r)</span>);
    layoutService.setActionItems(
        <>
            <mwc-icon-button icon="file_download" />
            <mwc-icon-button icon="print" />
            <mwc-icon-button icon="favorite" />
        </>,
    );

    return (
        <>
            <div className="centered">
                <img alt="Homer" src="/images/homer.jpg" />
                <Link to="/hello-world">Hello, World!</Link>
            </div>
        </>
    );
}

export default Home;

// svelte/src/pages/Home.svelte
<script type="ts">
    import Layout from "./Layout.svelte";
</script>

<Layout>
    <div slot="title">Home(r)</div>
    <div slot="actionItems">
        <mwc-icon-button icon="file_download" />
        <mwc-icon-button icon="print" />
        <mwc-icon-button icon="favorite" />
    </div>

    <div class="centered">
        <img alt="Homer" src="/images/homer.jpg" />
        <a href="#/hello-world">Hello, World!</a>
    </div>
</Layout>

<style>
    .centered {
        align-items: center;
        display: flex;
        flex-direction: column;
        justify-items: center;
    }
    img {
        width: 400px;
    }
</style>
