// svelte/src/pages/HelloWorld/index.svelte
<script type="ts">
    import HelloWorldForm from "./HelloWorldForm.svelte";
    import HelloWorldGeneratorButton from "./HelloWorldGeneratorButton.svelte";
    import HelloWorldList from "./HelloWorldList.svelte";
    import Layout from "../Layout.svelte";
    import { helloWorldService } from "shared";

    helloWorldService.searchHelloWorlds().subscribe();
    let hasMessages$ = helloWorldService.hasMessages$;
</script>

<Layout>
    <div slot="title">Hello, world!</div>
    <div slot="actionItems">
        <HelloWorldGeneratorButton />
    </div>
    <div class="container">
        <div class="grid">
            <div>
                <h2>Say Hello</h2>
                <div class="mdc-card padded">
                    <HelloWorldForm />
                </div>
            </div>
            {#if $hasMessages$}
                <div>
                    <h2>Who's Said Hello</h2>
                    <div class="mdc-card list">
                        <HelloWorldList />
                    </div>
                </div>
            {/if}
        </div>
    </div>
</Layout>

<style>
    .container {
        display: flex;
        align-items: center;
        justify-content: center;
    }
    .grid {
        align-items: flex-start;
        display: grid;
        grid-template-columns: 250px 1fr;
        grid-gap: 16px;
        margin: 16px;
    }

    .mdc-card.list {
        max-width: 400px;
        min-width: 250px;
        width: max-content;
    }

    .padded {
        padding: 16px;
    }

    @media (max-width: 600px) {
        .grid {
            grid-template-columns: 1fr;
        }
    }
</style>

// react-app/src/pages/HelloWorld/HelloWorld.tsx
import { useEffect } from "react";
import { helloWorldService } from "shared/lib/public-api";
import { useObservable, useTitle } from "../../utils/hooks";
import "./HelloWorld.css";
import HelloWorldForm from "./HelloWorldForm";
import HelloWorldList from "./HelloWorldList";

function HelloWorld() {
    useTitle(<span>Hello, world!</span>);
    const hasMessages = useObservable(helloWorldService.hasMessages$, false);
    const totalMessages = useObservable(helloWorldService.totalMessages$, 0);

    useEffect(() => {
        helloWorldService.searchHelloWorlds().subscribe();
    }, []);

    let whoSaidHello = null;
    if (hasMessages) {
        whoSaidHello = (
            <div>
                <h2>Who's Said Hello ({totalMessages})</h2>
                <div className="mdc-card list">
                    <HelloWorldList />
                </div>
            </div>
        );
    }

    return (
        <div className="container">
            <div className="grid">
                <div>
                    <h2>Say Hello</h2>
                    <div className="mdc-card padded">
                        <HelloWorldForm />
                    </div>
                </div>
                {whoSaidHello}
            </div>
        </div>
    );
}

export default HelloWorld;
