// react/src/pages/HelloWorld/HelloWorld.tsx
import { useEffect } from "react";
import { helloWorldService } from "shared";
import { layoutService } from "../../services/LayoutService";
import { useObservable } from "../../utils/hooks";
import "./HelloWorld.css";
import HelloWorldForm from "./HelloWorldForm";
import HelloWorldGenerator from "./HelloWorldGenerator";
import HelloWorldList from "./HelloWorldList";

function HelloWorld() {
    layoutService.setTitle(<span>Hello, world!</span>);
    layoutService.setActionItems(
        <>
            <HelloWorldGenerator />
        </>,
    );

    const hasMessages = useObservable(helloWorldService.hasMessages$, false);
    const totalMessages = useObservable(helloWorldService.totalMessages$, 0);

    useEffect(() => {
        helloWorldService.searchHelloWorlds().subscribe();
    }, []);

    let whoSaidHello = null;
    if (hasMessages) {
        whoSaidHello = (
            <div>
                <h2>Who's Said Hello ({totalMessages})</h2>
                <div className="mdc-card list">
                    <HelloWorldList />
                </div>
            </div>
        );
    }

    return (
        <div className="container">
            <div className="grid">
                <div>
                    <h2>Say Hello</h2>
                    <div className="mdc-card padded">
                        <HelloWorldForm />
                    </div>
                </div>
                {whoSaidHello}
            </div>
        </div>
    );
}

export default HelloWorld;

// angular/src/app/pages/hello-world/hello-world.component.ts
import { Component, OnInit } from "@angular/core";
import { helloWorldService } from "shared";

@Component({
    selector: "app-hello-world",
    templateUrl: "./hello-world.component.html",
    styleUrls: ["./hello-world.component.css"],
})
export class HelloWorldComponent implements OnInit {
    helloWorldService = helloWorldService;

    ngOnInit(): void {
        helloWorldService.searchHelloWorlds().subscribe();
    }
}

<!-- <script type="ts">

</script> -->

<div class="container">
    <div class="grid">
        <div>
            <h2>Say Hello</h2>
            <div class="mdc-card padded">
                <app-hello-world-form></app-hello-world-form>
            </div>
        </div>
        <ng-container *ngIf="helloWorldService.totalMessages$ | async; let totalMessages">
            <div *ngIf="totalMessages > 0">
                <h2>Who's Said Hello ({{ totalMessages }})</h2>
                <div class="mdc-card list">
                    <app-hello-world-list></app-hello-world-list>
                </div>
            </div>
        </ng-container>
    </div>
</div>
