// svelte/src/pages/HelloWorld/HelloWorldList.svelte
<script type="ts">
    import "@material/mwc-icon";
    import "@material/mwc-list/mwc-list.js";
    import "@material/mwc-list/mwc-list-item.js";
    import { helloWorldService } from "shared";

    function deleteMessage(helloWorldId: string) {
        return helloWorldService.deleteHelloWorld({ helloWorldId }).subscribe();
    }

    function handleKeyUp(event: KeyboardEvent, helloWorldId: string) {
        if (event.code === "Delete") {
            event.preventDefault();
            deleteMessage(helloWorldId);
        }
    }

    let messages$ = helloWorldService.messages$;
</script>

<div class="items">
    <mwc-list rootTabbable>
        {#each $messages$ as message, messageIndex}
            {#if messageIndex > 0}
                <li divider role="separator" />
            {/if}
            <mwc-list-item tabindex="0" hasMeta on:keyup={(event) => handleKeyUp(event, message.id)}>
                <span>Hello, {message.name}!</span>
                <mwc-icon on:click={() => deleteMessage(message.id)} slot="meta">delete</mwc-icon>
            </mwc-list-item>
        {/each}
    </mwc-list>
    <mwc-button fullwidth on:click={() => helloWorldService.searchNext().subscribe()}>Load more</mwc-button>
</div>

<style>
    .items {
        align-items: stretch;
        display: flex;
        flex-direction: column;
    }

    mwc-list-item mwc-icon {
        visibility: hidden;
    }
    mwc-list-item:hover mwc-icon {
        visibility: visible;
    }
    mwc-icon:hover {
        color: var(--mdc-theme-primary, #0055cc);
    }
</style>

// angular/src/app/pages/hello-world/hello-world-list/hello-world-list.component.ts
import { Component, ElementRef, OnInit } from "@angular/core";
import "@material/mwc-icon";
import "@material/mwc-list/mwc-list";
import "@material/mwc-list/mwc-list-item";
import { helloWorldService } from "shared";

@Component({
    selector: "app-hello-world-list",
    templateUrl: "./hello-world-list.component.html",
    styleUrls: ["./hello-world-list.component.css"],
})
export class HelloWorldListComponent {
    helloWorldService = helloWorldService;

    constructor(private elementRef: ElementRef) {}

    deleteMessage(helloWorldId: string) {
        return helloWorldService.deleteHelloWorld({ helloWorldId }).subscribe();
    }

    handleKeyUp(event: KeyboardEvent, helloWorldId: string) {
        if (event.code === "Delete") {
            event.preventDefault();
            this.deleteMessage(helloWorldId);
        }
    }

    handleLoadMoreClick() {
        helloWorldService.searchNext().subscribe();
    }
}

<div class="items">
    <mwc-list rootTabbable>
        <ng-container *ngFor="let message of helloWorldService.messages$ | async; index as messageIndex">
            <li *ngIf="messageIndex > 0" divider role="separator"></li>
            <mwc-list-item tabindex="0" hasMeta (keyup)="handleKeyUp($event, message.id)">
                <span>Hello, {{ message.name }}!</span>
                <mwc-icon (click)="deleteMessage(message.id)" slot="meta">delete</mwc-icon>
            </mwc-list-item>
        </ng-container>
    </mwc-list>
    <mwc-button fullwidth (click)="handleLoadMoreClick()">Load more</mwc-button>
</div>
