// react/src/pages/HelloWorld/HelloWorldList.tsx
import "@material/mwc-button";
import type { Button } from "@material/mwc-button";
import "@material/mwc-icon";
import "@material/mwc-list/mwc-list-item.js";
import "@material/mwc-list/mwc-list.js";
import { useEffect, useRef } from "react";
import { helloWorldService } from "shared";
import { useObservable } from "../../utils/hooks";
import "./HelloWorldList.css";

function HelloWorldList() {
    const messages = useObservable(helloWorldService.messages$, []);
    const loadMoreRef = useRef<Button>(null);

    const deleteMessage = (helloWorldId: string) => {
        return helloWorldService.deleteHelloWorld({ helloWorldId });
    };

    const handleLoadMoreClick = () => {
        helloWorldService.searchNext().subscribe();
    };

    const handleDeleteClick = (event: React.MouseEvent) => {
        const element = event.target as HTMLElement;
        if (element.localName === "mwc-icon") {
            const helloWorldId = element?.getAttribute("data-id");
            if (helloWorldId) {
                deleteMessage(helloWorldId).subscribe();
            }
        }
    };

    const handleKeyUp = (event: React.KeyboardEvent) => {
        const element = event.target as HTMLElement;
        if (element.localName === "mwc-list-item" && event.code === "Delete") {
            event.preventDefault();
            const helloWorldId = element?.getAttribute("data-id");
            if (helloWorldId) {
                const nextElement = element?.nextElementSibling as HTMLElement;
                deleteMessage(helloWorldId).subscribe(() => {
                    if (nextElement) {
                        nextElement.focus();
                    }
                });
            }
        }
    };

    useEffect(() => {
        const loadMoreButton = loadMoreRef.current;
        loadMoreButton?.addEventListener("click", handleLoadMoreClick);
        return () => {
            loadMoreButton?.removeEventListener("click", handleLoadMoreClick);
        };
    }, []);

    const messageListItems = messages.map((message) => (
        <mwc-list-item data-id={message?.id} key={message?.id} tabindex="0" hasMeta>
            <span>Hello, {message?.name}!</span>
            <mwc-icon data-id={message?.id} slot="meta">
                delete
            </mwc-icon>
        </mwc-list-item>
    ));

    return (
        <div className="items" onClick={handleDeleteClick} onKeyUp={handleKeyUp}>
            <mwc-list rootTabbable>{messageListItems}</mwc-list>
            <mwc-button fullwidth ref={loadMoreRef}>
                Load more
            </mwc-button>
        </div>
    );
}

export default HelloWorldList;

// angular/src/app/pages/hello-world/hello-world-list/hello-world-list.component.ts
import { Component, ElementRef, OnInit } from "@angular/core";
import "@material/mwc-icon";
import "@material/mwc-list/mwc-list";
import "@material/mwc-list/mwc-list-item";
import { helloWorldService } from "shared";

@Component({
    selector: "app-hello-world-list",
    templateUrl: "./hello-world-list.component.html",
    styleUrls: ["./hello-world-list.component.css"],
})
export class HelloWorldListComponent {
    helloWorldService = helloWorldService;

    constructor(private elementRef: ElementRef) {}

    deleteMessage(helloWorldId: string) {
        return helloWorldService.deleteHelloWorld({ helloWorldId }).subscribe();
    }

    handleKeyUp(event: KeyboardEvent, helloWorldId: string) {
        if (event.code === "Delete") {
            event.preventDefault();
            this.deleteMessage(helloWorldId);
        }
    }

    handleLoadMoreClick() {
        helloWorldService.searchNext().subscribe();
    }
}

<div class="items">
    <mwc-list rootTabbable>
        <ng-container *ngFor="let message of helloWorldService.messages$ | async; index as messageIndex">
            <li *ngIf="messageIndex > 0" divider role="separator"></li>
            <mwc-list-item tabindex="0" hasMeta (keyup)="handleKeyUp($event, message.id)">
                <span>Hello, {{ message.name }}!</span>
                <mwc-icon (click)="deleteMessage(message.id)" slot="meta">delete</mwc-icon>
            </mwc-list-item>
        </ng-container>
    </mwc-list>
    <mwc-button fullwidth (click)="handleLoadMoreClick()">Load more</mwc-button>
</div>
