// angular/src/app/pages/hello-world/hello-world-form/hello-world-form.component.ts
import { AfterContentInit, Component, ElementRef, ViewChild } from "@angular/core";
import "@material/mwc-button";
import "@material/mwc-textfield";
import type { TextField } from "@material/mwc-textfield";
import { helloWorldService } from "shared";

@Component({
    selector: "app-hello-world-form",
    templateUrl: "./hello-world-form.component.html",
    styleUrls: ["./hello-world-form.component.css"],
})
export class HelloWorldFormComponent implements AfterContentInit {
    isValid = false;
    @ViewChild("form")
    form: ElementRef<HTMLFormElement>;
    name: TextField & HTMLElement;

    constructor(private elementRef: ElementRef) {
        this.handleNameInvalid.bind(this);
        this.handleKeyUp.bind(this);
        this.handleSubmit.bind(this);
    }

    checkValidity(): boolean {
        return this.form.nativeElement.checkValidity() && this.name.checkValidity();
    }

    clearForm(): void {
        this.name.value = "";
        this.name.focus();
    }

    getFormData(): any {
        const formData = new FormData(this.form.nativeElement);
        const data: any = {};
        formData.forEach((value, key) => (data[key] = value));
        return data;
    }

    handleFormDataChanged(event: Event) {
        this.isValid = this.checkValidity();
    }

    handleKeyUp(event: KeyboardEvent) {
        if (event.code === "Enter") {
            event.preventDefault();
            this.handleSubmit(event);
        }
    }

    handleNameInvalid(event: Event) {
        this.isValid = false;

        this.name.validationMessage = "";
        if (this.name.validity.valueMissing) {
            this.name.validationMessage = "Name is required";
        } else if (this.name.validity.tooShort) {
            this.name.validationMessage = `Name must be at least ${this.name.getAttribute(
                "minlength",
            )} characters long`;
        } else if (this.name.validity.customError) {
            this.name.validationMessage = "Names starting with 'D' must be 'Doug'";
        }
    }

    handleSubmit(event: Event) {
        event.preventDefault();

        if (!this.checkValidity()) {
            return;
        }

        // If succcessful, send data to server
        const data = this.getFormData();
        helloWorldService.createHelloWorld({ sayHelloCommandMessage: data }).subscribe(() => {
            this.clearForm();
        });
    }

    ngAfterContentInit(): void {
        this.name = this.elementRef.nativeElement.querySelector("mwc-textfield");

        this.name.validityTransform = (newValue, nativeValidity) => {
            if (newValue.startsWith("D") && newValue !== "Doug") {
                return {
                    ...nativeValidity,
                    customError: true,
                    valid: false,
                };
            }
            return nativeValidity;
        };

        this.name.focus();
    }
}

<form #form (change)="handleFormDataChanged($event)" (submit)="handleSubmit($event)">
    <div class="spaced">
        <mwc-textfield
            label="Hello, "
            minLength="2"
            name="name"
            placeholder="Name"
            required
            autoValidate
            (invalid)="handleNameInvalid($event)"
            (keyup)="handleKeyUp($event)"
        ></mwc-textfield>
    </div>
    <div class="right">
        <mwc-button [attr:disabled]="!isValid" raised (click)="handleSubmit($event)">Submit</mwc-button>
    </div>
</form>

// svelte/src/pages/HelloWorld/HelloWorldForm.svelte
<script type="ts">
    import "@material/mwc-button";
    import "@material/mwc-textfield";
    import type { TextField } from "@material/mwc-textfield";
    import { helloWorldService } from "shared";
    import { onMount, tick } from "svelte";

    let isValid = false;
    let form: HTMLFormElement;
    let name: TextField;

    function checkValidity(): boolean {
        return form.checkValidity() && name.checkValidity();
    }

    function clearForm(): void {
        name.value = "";
        name.focus();
    }

    function getFormData(): any {
        const formData = new FormData(form);
        const data = {};
        for (let [key, value] of formData) {
            data[key] = value;
        }
        return data;
    }

    function handleFormDataChanged(event: Event) {
        isValid = checkValidity();
    }

    function handleKeyup(event: KeyboardEvent) {
        if (event.code === "Enter") {
            event.preventDefault();
            handleSubmit(event);
        }
    }

    function handleNameInvalid(event: InputEvent) {
        isValid = false;

        name.validationMessage = "";
        if (name.validity.valueMissing) {
            name.validationMessage = "Name is required";
        } else if (name.validity.tooShort) {
            name.validationMessage = `Name must be at least ${name.getAttribute("minlength")} characters long`;
        } else if (name.validity.customError) {
            name.validationMessage = "Names starting with 'D' must be 'Doug'";
        }
    }

    function handleSubmit(event: Event) {
        event.preventDefault();

        if (!checkValidity()) {
            return;
        }

        // If succcessful, send data to server
        const data = getFormData();
        helloWorldService.createHelloWorld({ sayHelloCommandMessage: data }).subscribe(() => {
            clearForm();
        });
    }

    onMount(async () => {
        name.validityTransform = (newValue, nativeValidity) => {
            if (newValue.startsWith("D") && newValue !== "Doug") {
                return {
                    ...nativeValidity,
                    customError: true,
                    valid: false,
                };
            }
            return nativeValidity;
        };

        await tick();
        name.focus();
    });
</script>

<form bind:this={form} on:change={handleFormDataChanged} on:submit={handleSubmit}>
    <div class="spaced">
        <mwc-textfield
            bind:this={name}
            label="Hello, "
            minLength="2"
            name="name"
            placeholder="Name"
            required
            autoValidate
            on:invalid={handleNameInvalid}
            on:keyup={handleKeyup}
        />
    </div>
    <div class="right"><mwc-button disabled={!isValid} raised on:click={handleSubmit}>Submit</mwc-button></div>
</form>

<style>
    .spaced {
        margin-bottom: 16px;
    }

    .right {
        text-align: right;
    }
</style>
